image: python:3.7-alpine
stages:
  - pre-merge
  - deploy

pre-merge:
  stage: pre-merge
  script: 
    - pip install -r riscv_ctg/requirements.txt
    - pip install --editable .
    - riscv_ctg --help
    - riscv_ctg --version
    - riscv_ctg -r -d rv32i -x 32 -cf sample_cgfs/rv32i.cgf -v debug -p8
    - riscv_ctg -r -d rv32im -x 32 -cf sample_cgfs/rv32im.cgf -v debug -p8
    - riscv_ctg -r -d rv32ic -x 32 -cf sample_cgfs/rv32ic.cgf -v debug -p8
    - riscv_ctg -r -d rv32i_priv -x 32 -cf sample_cgfs/rv32i_priv.cgf -v debug -p8
    - riscv_ctg -r -d rv64i -x 64 -cf sample_cgfs/rv64i.cgf -v debug -p8
    - riscv_ctg -r -d rv64im -x 64 -cf sample_cgfs/rv64im.cgf -v debug -p8
    - riscv_ctg -r -d rv64ic -x 64 -cf sample_cgfs/rv64ic.cgf -v debug -p8
    - riscv_ctg -r -d rv64i_priv -x 64 -cf sample_cgfs/rv64i_priv.cgf -v debug -p8
    - cd tests/
    - pytest test_riscv_ctg.py -v

  only:
    refs:
      - merge_requests

deploy:
  stage: deploy
  script:
        - pip install twine
        - python setup.py sdist
        - python -m twine upload --username $pypiusername --password $pypipassword dist/*
        - python /scratch/version-extract-rst.py
  only:
    refs:
      - master
  tags:
    - incore-group
  except:
    - schedules

